version = 0.1
[default.deploy.parameters]
stack_name = "event"
resolve_s3 = true
s3_prefix = "event"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
